name = "mozart409-zola-blog"
compatibility_date = "2026-01-22"
preview_urls = true

[[routes]]
pattern = "blog.mozart409.com"
custom_domain = true

[build]
command = "./build.sh"

[assets]
directory = "./blog/public"


[observability]
enabled = true
head_sampling_rate = 0.5
[observability.logs]
enabled = true 
invocation_logs = true
[observability.traces]
enabled = true 
head_sampling_rate = 0.5
