name = "mozart409-zola-blog"
compatibility_date = "2025-01-19"
main = "workers-site/index.js"

[site]
bucket = "./blog/public"

[build]
command = "cd blog && curl -fsSL https://github.com/getzola/zola/releases/download/v0.22.1/zola-v0.22.1-x86_64-unknown-linux-gnu.tar.gz | tar xz && ./zola build"
